# Site settings
title: Cute Zombies
email: contact.huydung@gmail.com
url: https://github.com/huydung/cute-zombies
description: "Website for Cute Zombies team - passionate Vietnamese people who make free, fun, educational games."
keywords: "games, video games, indie, educational, fun, free, game"
skills: "Fun, educational games. 100% Free. NO Ads!"
meta_author: Cute Zombies

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 6F2F9F #80B3FF
  primary-rgb: "111, 47, 159" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Cute Zombies Team
  location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/huydung1406/
  - title: linkedin
    url: https://www.linkedin.com/in/nguyenhuydung
  - title: github
    url: https://github.com/huydung
  - title: youtube
    url: https://www.youtube.com/@huydungcom

# Postal address (add as many lines as necessary)
address:
  - line: Nam Từ Liêm, Hà Nội, Việt Nam

# Credits content
credits: #'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
